sudo: required
services:
  - docker

script:
  - docker build -t nreoch9/with-apollo:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nreoch9/with-apollo:latest
